### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by simoncoles** [Better-Conversations/flightplan-sources#12]
Give us a simple command to lint the flightplans:

Does the time add up?

Spelling
  - Use aspell or something
  - We'll need an additional list of words to whitelist

**Comment by joshuacoles** [comment]
I have added basic linting for data validation issues that are outputted to the pipeline but they are not surfaced well. I think we need to decide what we want to show where, and what we want to warn about vs stop the build pipeline.

**Comment by simoncoles** [comment]
I think we need to be able to lint in the dev environment, doing it in the pipeline alone will drive us crazy
