### ISSUE TITLE
[OBS] Module 1 flight plan has incorrect Fx assignment

### ISSUE THREAD

**Issue by chandima-d** [Better-Conversations/flightplan-sources#23]
*This is a public site so please only identify people with their agreement*

**Module: 1** 
**Course version:** (leave blank for current version)

**What did you notice?** 

Fx2 is down to close - this needs to be Fx1.

**Anything else about that?**

Check other Modules for Fx order

**What do you think should happen?**

Make sure Fx1/Fx2 segments are consistent and in line with the course overview

**Comment by joshuacoles** [comment]
This is resolved in #25

**Comment by joshuacoles** [comment]
For module 1 that is

**Comment by chandima-d** [comment]
I think this overlaps with the common blocks issue ([BCF-397](https://linear.app/amphora/issue/BCF-397/parameterise-passing-the-lead-facilitator-into-common-blocks))

**Comment by chandima-d** [comment]
Resolved in v3.0.3
