### ISSUE TITLE
Sort out resources section comments

### ISSUE THREAD

**Issue by chandima-d** [Better-Conversations/flightplan-sources#7]
Original flight plans have comments such as:
![image](https://github.com/user-attachments/assets/9f2d2a37-c8aa-49fd-b6ba-20e435680086)

New flight plans have this slight reordering which needs to move the scribe up in the order (as per original flight plan)
![image](https://github.com/user-attachments/assets/b7116d48-e498-4867-a8aa-1c94cfb783f8)

Also need to add highlighting for Fx2. This is so the roles are clear.

**Comment by joshuacoles** [comment]
![CleanShot 2024-10-08 at 12 18 25@2x](https://github.com/user-attachments/assets/7aebd421-d7bf-4dfc-9e5d-3ef647bca94c)
The DC now looks like this, what do you think @chandima-d ?

**Comment by joshuacoles** [comment]
We will also need to update the PDF exports

**Comment by chandima-d** [comment]
Changes made for v3.0.3 of flight plans
